server:
  port: 8080
spring:
  thymeleaf:
    prefix: file:src/main/resources/templates/
    cache: false
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://localhost:3306/university
    username: viktoria
    password: 14082001
